### ISSUE TITLE
Error: conflict: constraint underscore@1.0.1 is not satisfied by 1.0.1-win.0

### ISSUE THREAD

**Issue by vjau** [meteor/windows-preview#2] opened 2014-11-20 11:39 UTC
Hi,
while trying to add a local package with meteor add foo
which use underscore    api.use('underscore')
i get the following error:
Could not satisfy all the specified constraints:
Error: conflict: constraint underscore@1.0.1 is not satisfied by 1.0.1-win.0.
Constraints on underscore come from:
  <top level>
  cadendar-consts@1.0.0 -> cadendar-utils@1.0.0
  cadendar-consts@1.0.0 -> vjau-enums@1.0.0
  meteor-platform@1.2.0-win.0
  meteor-platform@1.2.0-win.0 -> meteor@1.1.3-win.0

**Comment by stubailo** [comment] 2015-01-22 22:10
I'm going to close this because this discussion is better had on a separate issue.

**Closed by stubailo** 2015-01-22 22:10 UTC

**Comment by dandv** [comment] 2015-01-31 22:03
@stubailo: was the info on those registry keys useful? Since removing them fixed the problem, maybe the installer can start by cleaning up the registry and deleted `%USERPROFILE%\AppData\Local\.meteor`, and the `meteorsession` file if necessary.

If the current installer does that, nevermind my comment. The problem is I keep getting the [Access denied](https://github.com/meteor/windows-preview/issues/31#issuecomment-70095229) exception.

**Comment by Slava** [comment] 2015-01-31 22:05
@dandv our new installer is going to be built with WiX so hopefully we will not have any troubles with registry keys.
