### ISSUE TITLE
failed to call netstat.exe

### ISSUE THREAD

**Issue by landmaxcanada** [meteor/windows-preview#88] opened 2015-03-07 19:19 UTC
Hi, just tried 0.2.0 and get:

>meteor
>C:\Users\James\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.wi
>ndows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
>                                                throw(ex);
>                                                     ^
>Error: Couldn't run netstat -ano: {}
    at Object.Future.wait (C:\Users\James\AppData\Local\.meteor\packages\meteor-
tool\1.1.0-winr.12\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\futur
e.js:398:15)

FYI - "Meteor List" works
>C:\code\kudu\apps\test1\site\wwwroot>meteor list
autopublish      1.0.3-winr.2  Publish the entire database to all clients
insecure         1.0.3-winr.2  Allow all database writes by default
meteor-platform  1.2.2-winr.3  Include a standard set of Meteor packages...

I got this error with previous versions and would run the "fix" update command, but that is no longer listed in the wiki.

Tried meteor update:

>C:\code\kudu\apps\test1\site\wwwroot> meteor update
This project is already at Meteor 0.2.0, the latest release.
Your packages are at their latest compatible versions.

**Comment by Slava** [comment] 2015-03-07 20:19
Looks like you don't have cli utility called netstat? Can you show us the output of the following commands from cmd.exe?

   where netstat
   Echo %path%

**Comment by landmaxcanada** [comment] 2015-03-07 20:48
>C:\code\kudu\apps\test1\site\wwwroot>where netstat
C:\Windows\System32\NETSTAT.EXE

>C:\code\kudu\apps\test1\site\wwwroot>Echo %path%
C:\Program Files (x86)\PHP\v5.4;C:\Windows\system32\inetsrv;C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program
Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platfo
rm Installer\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SDKs\Azu
re\CLI\wbin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\James
\AppData\Local\.meteor;c:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Page
s\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Microsoft SDKs\Typ
eScript\1.4\;C:\Users\James\AppData\Local\.meteor;C:\Users\James\AppData\Roaming
\npm;C:\Users\James\AppData\Local\.meteor\

**Comment by Slava** [comment] 2015-03-07 20:55
So yeah, the error comes from here: https://github.com/meteor/meteor/blob/47f463d6b6dac6305fd9a02aea3c5d2e41492e72/tools/run-mongo.js#L87. The line just calls your netstat. Looking at the output you provided, netstat exists and is accessible from `PATH`. At this point I have no idea why it can happen.

**Comment by landmaxcanada** [comment] 2015-03-07 21:08
I did not mention that this was Windows Server 2012 R2 running on Azure.  I have been playing with Hosting on Windows, but it may be faster to learn Ubuntu ;)

**Comment by stubailo** [comment] 2015-03-20 18:23
Duplicate of #85

**Closed by stubailo** 2015-03-20 18:23 UTC

**Comment by stuartbale** [comment] 2015-04-01 01:22
I have the same error on Windows Server 2012 R2. I am running command prompt as Admin.

I can run netstat from the same command line.

So what is the fix?

C:\meteor\simple-todos>meteor
[[[[[ C:\meteor\simple-todos ]]]]]

=> Started proxy.

C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local\.meteor\packages\meteor-too
l\1.1.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: Couldn't run netstat -ano: {}
    at Object.Future.wait (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at findMongoPids (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:120:16)
    at findMongoAndKillItDead (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Lo
cal\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:2
36:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Users\Administrator.WIN-OE3C
006M71I\AppData\Local\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\to
ols\run-mongo.js:360:7)
    at launchMongo (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local\.meteor
\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:612:7)
    at [object Object]._.extend._startOrRestart (C:\Users\Administrator.WIN-OE3C
006M71I\AppData\Local\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\to
ols\run-mongo.js:712:19)
    at [object Object]._.extend.start (C:\Users\Administrator.WIN-OE3C006M71I\Ap
pData\Local\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mo
ngo.js:670:10)
    at C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local\.meteor\packages\met
eor-tool\1.1.1\mt-os.windows.x86_32\tools\run-all.js:199:26
    - - - - -
    at C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local\.meteor\packages\met
eor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:89:28
    at ChildProcess.exithandler (child_process.js:654:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
