### ISSUE TITLE
Error: EBADF, read

### ISSUE THREAD

**Issue by bluebay** [meteor/windows-preview#100] opened 2015-03-15 04:04 UTC
For some reason, I keep seeing these messages on Meteor console

W20150315-09:10:04.636(5.5)? (STDERR) Error: EBADF, read
W20150315-09:10:04.639(5.5)? (STDERR) Error: EBADF, read
W20150315-09:10:05.099(5.5)? (STDERR) Error: EBADF, read
W20150315-09:10:05.349(5.5)? (STDERR) Error: OK, read
W20150315-09:10:05.544(5.5)? (STDERR) Error: EBADF, read
W20150315-09:10:05.605(5.5)? (STDERR) Error: EBADF, read

However, they dont affect anything, I guess.

**Comment by Slava** [comment] 2015-03-18 17:44
It is a Windows' "Bad File" error by looks at it. Does it happen on any app or some particular app? Do you know your version of file system?

**Comment by stubailo** [comment] 2015-03-20 18:21
Duplicate of #130

**Closed by stubailo** 2015-03-20 18:21 UTC

**Comment by bluebay** [comment] 2015-04-27 00:58
@Slava Sorry, did not read your comment. @stubailo thanks for pointing out.
