### ISSUE TITLE
Not able to install meteor using git bash on Windows OS

### ISSUE THREAD

**Issue by Shekharrajak** [meteor/windows-preview#167] opened 2015-06-02 11:09 UTC
If we install meteor using cmd then it works fine ,but we generally prefer git bash during our work like herolu ,modulus etc .
When I tried to install meteor using git bash ,it show OS is not  supported yet.
Is there any way to install meteor using git bash or after installing this  on cmd can we use meteor on git bash as well , like heroku.

**Comment by sdarnell** [comment] 2015-06-03 07:27
When you say install, what did you use? The curl command or the MSI based installer? My guess is the former.

This won't work as the script that the curl command downloads is for Unix based machines.

However, I think the script could give a better message telling you what to do.

**Comment by Shekharrajak** [comment] 2015-06-03 08:57
But curl is installed automatically when we install git bash in windows,right ?
![curl](https://cloud.githubusercontent.com/assets/5774448/7956269/7276c668-09fc-11e5-9a22-13100089d6a0.PNG)

No,we don't get message telling what to do.

Is there any method to install meteor using git bash in windows ?

**Comment by sdarnell** [comment] 2015-06-09 19:56
Maybe I wasn't very clear.

Just because you have a bash shell and curl doesn't mean that the linux/mac way of installing meteor will work on Windows. There are other Windows dependencies that mean you still need to use the MSI based installer on Windows.  Luckily you can install MSI packages via the command line using the `msiexec` tool. (Google for full options, but you basically need `msiexec /i package.msi`)

My other point was that instead of giving a message that the OS is not supported, it would be more helpful if the unix meteor installation script gave a clearer message indicating that you need to use the MSI installer on Windows.

**Comment by stubailo** [comment] 2015-06-09 20:44
@sdarnell the actual issue is that the Meteor installation comes with two scripts: `meteor.bat` and `meteor`.

When you are running in CMD or PowerShell, it automatically runs the Windows specific script for you. If you are in Git Bash, it runs `meteor`, which currently only works on Mac/Linux. Maybe there is a simple solution of putting something at the top of `meteor` that runs the Windows script if it is inside Bash on Windows.

**Comment by Slava** [comment] 2015-06-09 20:48
Presumably we can parse the output of `uname` and search for something resembling "mingw" in the string. Also, we don't put a bash script for Windows bootstrap tarballs.

**Comment by Shekharrajak** [comment] 2015-06-10 06:24
Ok ,it is clear that we can't install meteor using git bash directly in windows, but why we can't use git bash while meteor is installed using cmd ?
None of the meteor command is working but we can use npm commands which is installed during meteor installation on git bash.

**Comment by stubailo** [comment] 2015-08-11 18:49
Duplicate of #96

**Closed by stubailo** 2015-08-11 18:49 UTC
