### ISSUE TITLE
0x80070643 - Fatal error during installation

### ISSUE THREAD

**Issue by ManuelDeLeon** [meteor/windows-preview#86] opened 2015-03-06 23:30 UTC
Got this error installing 0.2.0 on top of the previous version (0.1.7)...
```
[0DE4:32E0][2015-03-06T16:21:34]i001: Burn v3.8.1128.0, Windows v6.1 (Build 7601: Service Pack 1), path: C:\Users\Manuel\Downloads\InstallMeteor.exe, cmdline: '-burn.unelevated BurnPipe.{8FC7092D-C3D5-40F8-B85B-82E3117A601F} {F0B3980F-6E96-4849-A181-3EF66F3FFEC8} 9880'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'TermsUrl' to value 'https://www.meteor.com/terms'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'PrivacyUrl' to value 'https://www.meteor.com/privacy'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing numeric variable 'PerMachineInstall' to value '0'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing numeric variable 'PerUserInstall' to value '1'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing numeric variable 'CreateRButton' to value '1'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing numeric variable 'SignInRButton' to value '0'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing hidden variable 'RegisterEmail'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing hidden variable 'RegisterUser'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing hidden variable 'RegisterPass'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'SkipRegistrationState' to value 'disable'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing numeric variable 'SkipRegistration' to value '0'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'UserMeteorSessionFile' to value '[LocalAppDataFolder]\.meteorsession'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'PerMachineInstallFolder' to value '[ProgramFilesFolder][WixBundleName]'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'PerUserInstallFolder' to value '[LocalAppDataFolder]'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'InstallFolder' to value '[PerUserInstallFolder]'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'InstallRegPath' to value 'SOFTWARE\Meteor Development Group \Meteor\Install'
[0DE4:32E0][2015-03-06T16:21:34]i000: Initializing string variable 'MSICustomErrFile' to value '[WixBundleLog].err'
[0DE4:32E0][2015-03-06T16:21:34]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\Manuel\AppData\Local\Temp\Meteor_20150306162134.log'
[0DE4:32E0][2015-03-06T16:21:34]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\Manuel\Downloads\InstallMeteor.exe'
[0DE4:32E0][2015-03-06T16:21:34]i052: Condition '(VersionNT >= v5.1)' evaluates to true.
[0DE4:32E0][2015-03-06T16:21:34]i000: Setting string variable 'WixBundleName' to value 'Meteor'
[0DE4:33A8][2015-03-06T16:21:35]i000: Setting string variable 'varProgressHeader' to value 'Installing [WixBundleName]'
[0DE4:33A8][2015-03-06T16:21:35]i000: Setting string variable 'varProgressInfo' to value 'Please wait while Setup installs [WixBundleName] on your computer.'
[0DE4:33A8][2015-03-06T16:21:35]i000: Setting string variable 'varSuccessHeader' to value 'Meteor Installed'
[0DE4:33A8][2015-03-06T16:21:35]i000: Setting string variable 'varSuccessInfo' to value 'Meteor is now installed on your computer.

Open a new command prompt and run "meteor".'
[0DE4:33A8][2015-03-06T16:21:35]i000: Setting string variable 'varFailureHeader' to value 'Setup Failed'
[0DE4:32E0][2015-03-06T16:21:35]i100: Detect begin, 2 packages
[0DE4:32E0][2015-03-06T16:21:35]i000: Update location: https://www.meteor.com/.
[0DE4:32E0][2015-03-06T16:21:35]i101: Detected package: SetupMeteor_MachineInstall, state: Absent, cached: None
[0DE4:32E0][2015-03-06T16:21:35]i101: Detected package: SetupMeteor_UserInstall, state: Absent, cached: None
[0DE4:32E0][2015-03-06T16:21:35]i199: Detect complete, result: 0x0
[0DE4:33A8][2015-03-06T16:21:37]i000: Setting numeric variable 'CreateRButton' to value 0
[0DE4:33A8][2015-03-06T16:21:37]i000: Setting numeric variable 'SignInRButton' to value 0
[0DE4:33A8][2015-03-06T16:21:37]i000: Setting hidden variable 'RegisterEmail'
[0DE4:33A8][2015-03-06T16:21:37]i000: Setting hidden variable 'RegisterUser'
[0DE4:33A8][2015-03-06T16:21:37]i000: Setting hidden variable 'RegisterPass'
[0DE4:33A8][2015-03-06T16:21:37]i000: Setting numeric variable 'SkipRegistration' to value 0
[0DE4:32E0][2015-03-06T16:21:37]i200: Plan begin, 2 packages, action: Install
[0DE4:32E0][2015-03-06T16:21:37]i052: Condition 'NOT Installed AND (PerMachineInstall = 1)' evaluates to false.
[0DE4:32E0][2015-03-06T16:21:37]w322: Skipping cross-scope dependency registration on package: SetupMeteor_MachineInstall, bundle scope: PerUser, package scope: PerMachine
[0DE4:32E0][2015-03-06T16:21:37]i052: Condition 'NOT Installed AND (PerUserInstall = 1)' evaluates to true.
[0DE4:32E0][2015-03-06T16:21:37]i000: Setting string variable 'WixBundleRollbackLog_SetupMeteor_UserInstall' to value 'C:\Users\Manuel\AppData\Local\Temp\Meteor_20150306162134_0_SetupMeteor_UserInstall_rollback.log'
[0DE4:32E0][2015-03-06T16:21:37]i000: Setting string variable 'WixBundleLog_SetupMeteor_UserInstall' to value 'C:\Users\Manuel\AppData\Local\Temp\Meteor_20150306162134_0_SetupMeteor_UserInstall.log'
[0DE4:32E0][2015-03-06T16:21:37]i201: Planned package: SetupMeteor_MachineInstall, state: Absent, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[0DE4:32E0][2015-03-06T16:21:37]i201: Planned package: SetupMeteor_UserInstall, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: Uninstall, cache: Yes, uncache: No, dependency: Register
[0DE4:32E0][2015-03-06T16:21:37]i299: Plan complete, result: 0x0
[0DE4:32E0][2015-03-06T16:21:37]i300: Apply begin
[0DE4:32E0][2015-03-06T16:21:37]i000: Caching bundle from: 'C:\Users\Manuel\AppData\Local\Temp\{1474e220-151a-45a3-86b8-b3ee16c36bb8}\.be\Setup_Meteor.exe' to: 'C:\Users\Manuel\AppData\Local\Package Cache\{1474e220-151a-45a3-86b8-b3ee16c36bb8}\Setup_Meteor.exe'
[0DE4:32E0][2015-03-06T16:21:37]i320: Registering bundle dependency provider: {1474e220-151a-45a3-86b8-b3ee16c36bb8}, version: 0.2.0.0
[0DE4:3670][2015-03-06T16:21:38]i305: Verified acquired payload: SetupMeteor_UserInstall at path: C:\Users\Manuel\AppData\Local\Package Cache\.unverified\SetupMeteor_UserInstall, moving to: C:\Users\Manuel\AppData\Local\Package Cache\{D6252E9C-67B6-431C-95B7-F8DD8A1FB48B}v0.2.0\SetupMeteor.msi.
[0DE4:32E0][2015-03-06T16:21:38]i323: Registering package dependency provider: {D6252E9C-67B6-431C-95B7-F8DD8A1FB48B}, version: 0.2.0, package: SetupMeteor_UserInstall
[0DE4:32E0][2015-03-06T16:21:38]i301: Applying execute package: SetupMeteor_UserInstall, action: Install, path: C:\Users\Manuel\AppData\Local\Package Cache\{D6252E9C-67B6-431C-95B7-F8DD8A1FB48B}v0.2.0\SetupMeteor.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" METEOR_DIR="C:\Users\Manuel\AppData\Local\" INSTALL_REG_PATH="SOFTWARE\Meteor Development Group \Meteor\Install" MSICUSTOMERRFILE="C:\Users\Manuel\AppData\Local\Temp\Meteor_20150306162134.log.err" PERUSER_INSTALL="1"'
[0DE4:32E0][2015-03-06T16:21:55]e000: Error 0x80070643: Failed to install MSI package.
[0DE4:32E0][2015-03-06T16:21:55]e000: Error 0x80070643: Failed to configure per-user MSI package.
[0DE4:32E0][2015-03-06T16:21:55]i319: Applied execute package: SetupMeteor_UserInstall, result: 0x80070643, restart: None
[0DE4:32E0][2015-03-06T16:21:55]e000: Error 0x80070643: Failed to execute MSI package.
[0DE4:32E0][2015-03-06T16:21:55]i318: Skipped rollback of package: SetupMeteor_UserInstall, action: Uninstall, already: Absent
[0DE4:32E0][2015-03-06T16:21:55]i319: Applied rollback package: SetupMeteor_UserInstall, result: 0x0, restart: None
[0DE4:32E0][2015-03-06T16:21:55]i329: Removed package dependency provider: {D6252E9C-67B6-431C-95B7-F8DD8A1FB48B}, package: SetupMeteor_UserInstall
[0DE4:32E0][2015-03-06T16:21:55]i351: Removing cached package: SetupMeteor_UserInstall, from path: C:\Users\Manuel\AppData\Local\Package Cache\{D6252E9C-67B6-431C-95B7-F8DD8A1FB48B}v0.2.0\
[0DE4:32E0][2015-03-06T16:21:55]i330: Removed bundle dependency provider: {1474e220-151a-45a3-86b8-b3ee16c36bb8}
[0DE4:32E0][2015-03-06T16:21:55]i352: Removing cached bundle: {1474e220-151a-45a3-86b8-b3ee16c36bb8}, from path: C:\Users\Manuel\AppData\Local\Package Cache\{1474e220-151a-45a3-86b8-b3ee16c36bb8}\
[0DE4:32E0][2015-03-06T16:21:55]i399: Apply complete, result: 0x80070643, restart: None, ba requested restart:  No
```

**Comment by stubailo** [comment] 2015-03-06 23:32
@ManuelDeLeon were you installing from the CLI?

**Comment by ManuelDeLeon** [comment] 2015-03-06 23:33
nope, I used the new InstallMeteor.exe

**Comment by ManuelDeLeon** [comment] 2015-03-06 23:35
btw, that was the log file. The setup wizard only said "0x80070643 - Fatal error during installation. See log file."

**Comment by stubailo** [comment] 2015-03-06 23:37
Oh, I see. Thanks!

**Comment by ManuelDeLeon** [comment] 2015-03-07 16:40
I removed meteor but got the error again. I ran the installer as an admin and it worked...

**Comment by robbie2014** [comment] 2015-03-17 20:57
i have the same problem- even when I ran the installer as admin.

**Comment by stubailo** [comment] 2015-03-20 18:25
Duplicate of #125

**Closed by stubailo** 2015-03-20 18:25 UTC

**Comment by chesteremia** [comment] 2015-07-04 14:46
I also have the same error. I tried running the installer as admin but it doesn't work either. I tried turning off the firewall and still it doesn't work. what to do with this?
