### ISSUE TITLE
Error 'surprising path'

### ISSUE THREAD

**Issue by paulvanbladel** [meteor/windows-preview#37] opened 2015-01-22 08:23 UTC
Love the error message 'surprising path' :)
f:\GIT\Meteor\LobPatterns>meteor create meteorApp

C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
Error: Surprising path: /f/GIT/Meteor
    at toDosPath (C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\tools\files.js:1107:13)
    at C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\tools\files.js:1336:16
    at Array.map (native)
    at Function._.map._.collect (C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:97:56)
    at Object.pathDirname (C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\tools\files.js:1333:16)
    at findUpwards (C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\tools\files.js:55:24)
    at Object.files.findAppDir (C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\tools\files.js:88:10)
    at C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-os.windows.x86_32\tools\main.js:688:22
f:\GIT\Meteor\LobPatterns>

**Comment by esgy** [comment] 2015-01-22 13:59
same here.. tried every way possible to install and reinstall still get the 'surprising path'

**Comment by Slava** [comment] 2015-01-22 17:19
This is fixed on a branch but we are yet to release a new version. The workaround is to use capital letter for your disk.

    cd F:

**Comment by stubailo** [comment] 2015-01-22 21:58
Try preview 0.1.0: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

I think this issue should be fixed now.

**Comment by dovrosenberg** [comment] 2015-01-26 21:49
Still doing it in 0.1.1 when I use a subst drive ("Error: surprising path: /K")

I've tried all combinations of capitalization in both the target and the subst drive letters.  And works fine in the same directory if I use the full path.

**Comment by Slava** [comment] 2015-01-27 18:57
@dovrosenberg please give us more information on how to reproduce the problem. What path are you running from? What is the "full path" that you use to make it work? Do you have a disk K:?

**Comment by dovrosenberg** [comment] 2015-01-27 19:09
C:\Users\Dov>subst K: c:\users\dov\dropbox\development\

C:\Users\Dov>k:

K:\>meteor create test

C:\Users\Dov\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windo
ws.x86_32\dev_bundle\lib\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
Error: Surprising path: /K
    at toDosPath (C:\Users\Dov\AppData\Local\.meteor\packages\meteor-tool\1.1.0-
winr.0\mt-os.windows.x86_32\tools\files.js:1179:13)
    at C:\Users\Dov\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-o
s.windows.x86_32\tools\files.js:1402:16
    at Array.map (native)
    at Function._.map._.collect (C:\Users\Dov\AppData\Local\.meteor\packages\met
eor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscor
e\underscore.js:97:56)
    at Object.pathResolve (C:\Users\Dov\AppData\Local\.meteor\packages\meteor-to
ol\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:1399:16)
    at Object.files.mkdir_p (C:\Users\Dov\AppData\Local\.meteor\packages\meteor-
tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:370:17)
    at Object.files.mkdir_p (C:\Users\Dov\AppData\Local\.meteor\packages\meteor-
tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:382:23)
    at Object.files.cp_r (C:\Users\Dov\AppData\Local\.meteor\packages\meteor-too
l\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:431:9)
    at Command.buildCommands.minArgs [as func] (C:\Users\Dov\AppData\Local\.mete
or\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\commands.js:585:
11)
    at C:\Users\Dov\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-o
s.windows.x86_32\tools\main.js:1327:23

K:\> c:

C:\Users\Dov> cd dropbox\development

C:\Users\Dov\Dropbox\development> meteor create test

[executes successfully]

**Comment by Slava** [comment] 2015-01-27 19:36
@dovrosenberg thanks, fixed in https://github.com/meteor/meteor/commit/07fa40f20e280aa015659c4223e73e88cbe8bace

**Comment by dovrosenberg** [comment] 2015-01-27 19:45
Posting to confirm it works.  Thanks for the quick fix!

**Closed** 2015-01-27 19:52 UTC
Labels: fixed

**Comment by dandv** [comment] 2015-01-31 22:36
Was this pushed? I've just installed via the Windows installer, I'm on `C`, no subst drives, but there is a directory with `$` in its name: `c:\prg\met\$packages` (note - not `/prg/meteor/$packages` as the error claims).

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\A>cd \prg\met\

C:\prg\met>

C:\prg\met>meteor create webstormeteor

C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
Error: Surprising path: /prg/meteor/$packages
    at toDosPath (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:1179:13)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:1402:16
    at Array.map (native)
    at Function._.map._.collect (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:97:56)

    at Object.pathResolve (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:1399:16)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:449:31
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at ProjectContext._.extend._localPackageSearchDirs (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:448:9)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:478:33
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:471:20
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\catalog.js:92:31)
    at ProjectContext._.extend._initializeCatalog (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:470:13)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:214:35
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:204:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:192:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\project-context.js:197:10)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\commands.js:622:20
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.main.captureAndExit (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:261:29)
    at Command.buildCommands.minArgs [as func] (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\commands.js:607:8)
    at C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:1327:23
C:\prg\met>
```

**Comment by Slava** [comment] 2015-01-31 22:41
@dandv looks like the assertion is catching real errors?

> cd \prg\met\

is it really a valid way to change path? open a new issue please

**Comment by dandv** [comment] 2015-01-31 23:03
`cd \Windows` is a perfectly valid way to change the path. It means change to the `Windows` directory under the root directory of the current drive. Filed a separate issue.
