### ISSUE TITLE
Deployment from preview 0.1.17 crashes on Meteor hosting

### ISSUE THREAD

**Issue by robhalevt** [meteor/windows-preview#64] opened 2015-02-11 01:25 UTC
Working through the tutorial I got to step 6 (deploying) and while the command window resulted in a successful message that tells me:
`    Deploying to earing.meteor.com.`
`    Now serving at http://earing.meteor.com`

but when I go to the site it tells me:
`    This site has crashed.`
`    Site administrators can examine the logs with:`
`    meteor logs earing.meteor.com `

Looking at the log it says:
`    [Wed Feb 11 2015 01:16:09 GMT+0000 (UTC)] INFO HIT / 67.217.115.57`
`    [Wed Feb 11 2015 01:16:31 GMT+0000 (UTC)] NOTICE Starting application on port
    28870`
`    [Wed Feb 11 2015 01:16:31 GMT+0000 (UTC)] INFO STATUS waiting -> starting`
`    [Wed Feb 11 2015 01:16:31 GMT+0000 (UTC)] INFO STATUS starting -> running`
`    [Wed Feb 11 2015 01:16:32 GMT+0000 (UTC)] WARNING Meteor requires Node v0.10.36
or later.`
`    [Wed Feb 11 2015 01:16:32 GMT+0000 (UTC)] ERROR Application crashed with code:`
`    1`

But I don't know what code 1 would indicate.

**Comment by Slava** [comment] 2015-02-11 02:19
Please give us the full reproduction. If it is an app from the tutorial, you can give us the code in a form of a github repo.

**Comment by robhalevt** [comment] 2015-02-11 14:20
Created a repo for the code: https://github.com/robhalevt/MeteorTutorial

I didn't include the .meteor folder and its contents, let me know if you need that added.

**Comment by stubailo** [comment] 2015-02-11 17:09
Yes, we need the `.meteor` folder. In general, repositories of Meteor projects should always contain that folder.

**Comment by robhalevt** [comment] 2015-02-11 19:13
I've put the `.meteor` folder and its contents into the repository. I've excluded the `local` folder and *its* contents because my basic, git-noob config wants me to. Let me know if you need that as well.

**Comment by stubailo** [comment] 2015-02-11 20:29
`.meteor` should come with a default `.meteor/.gitignore` which does all of the right things, so you probably don't have to think about this stuff.

**Comment by robhalevt** [comment] 2015-02-11 21:35
That file is there, but git doesn't appear to be respecting it (maybe an issue with the Windows code?). Anyway, I've forced the folder structure into the repo.

**Comment by Slava** [comment] 2015-02-11 22:11
The file might just have incorrect end-of-line chars?

**Comment by stubailo** [comment] 2015-02-11 22:21
Oh, snap. I wonder if that's it.

**Comment by robhalevt** [comment] 2015-02-12 13:40
I don't know if it's helpful information for diagnosing but the editor used was SublimeText 2. I've opened the files in Notepad++ to see what the encoding is and it's **UTF-8 without BOM**. The EOL appears to be a LF.

**Comment by lpartan** [comment] 2015-02-14 09:53
/server/boot.js line 14 looks at process.version and exits with code 1 after issuing  WARNING Meteor requires Node v0.10.36 or later.  It never leaves the ground, never even ignites the engine..

**Comment by cparker4486** [comment] 2015-02-16 20:50
Not sure if it is helpful or not but +1 for me on this issue. I'm deploying my own simple(ish) app.

**Comment by GiraffeSlacks** [comment] 2015-02-16 21:54
I don't know if this is helpful but I'm having the same issue.

**Comment by lpartan** [comment] 2015-02-17 00:34
Here is a temporary solution that anyone can do:
--Change one line inside the file boot.js  that is located deep inside the appdata\local\.meteor folder.  

For example, on my PC, %localappdata% is "C:\Users\lpartan\AppData\Local".

The file should be (win8 YMMV) 
%localappdata%\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\server\boot.js

-- make line 17 a comment like this:    
        // process.exit(1)
-- save the file 
 
Now you can navigate to any of your meteor app folders, deploy to meteor.com, and it will run.

Changing any other boot.js file will not work.  Apparently when "deploy" runs, it grabs a fresh copy from %localappdata%  (( not using the boot.js that is inside your app folders )).

The next question is this:  what does line 16 process.version return?  It should be returning the version of NODE.JS on the host. why doesn't this check pass this gatekeeping test?

**Comment by lpartan** [comment] 2015-02-17 00:42
After newly deploying with boot.js modified to show the version, the log says: 
NOTICE Starting application on port 21473 
INFO STATUS starting -> running
WARNING This Node process version is reported as "v0.10.33".
WARNING Meteor requires Node v0.10.36 or later.

**Comment by lpartan** [comment] 2015-02-17 01:22
I suggest that line 12 of meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\server\boot.js
should set MIN_NODE_VERSION to  'v0.10.33'

**Comment by dandv** [comment] 2015-02-19 13:26
I had the same problem after running `meteor deploy webix` from http://github.com/dandv/meteor-webix

**Comment by ashbygreg** [comment] 2015-02-22 23:07
I had the same problem, the fix suggested by Ipartan worked for me, thanks!

**Comment by robhalevt** [comment] 2015-02-23 13:52
I realize this issue has been closed, but just to close the loop... I made [the change suggested by @lpartan ](https://github.com/meteor/windows-preview/issues/64#issuecomment-74603264) and the deployment works now.

**Comment by GiraffeSlacks** [comment] 2015-02-23 16:23
@robhalevt The issue is still open because, I presume, the bug has not been resolved yet. Only a workaround has been proposed. @Slava closed another issue as a duplicate of this one because it was opened later.

**Comment by Slava** [comment] 2015-02-24 04:40
I assume this happens because the Windows Preview is ahead of regular Meteor releases. This is why applications deployed from the preview require the version of node that is not yet on our free-tier hosting. Is it correct, @n1mmy?

**Comment by stubailo** [comment] 2015-02-24 18:01
AFAIK this should be fixed because the deploy server should have the right dev bundle version. We should look into this.

**Comment by n1mmy** [comment] 2015-02-25 05:27
Hrm... Looks like the deploy servers have up through `0.4.15`. So maybe that isn't the issue.

**Comment by Slava** [comment] 2015-03-05 00:23
Fixed on devel

**Closed by Slava** 2015-03-05 00:23 UTC
