### ISSUE TITLE
netstat or tasklist not found

### ISSUE THREAD

**Issue by thepowderriverfarrier** [meteor/windows-preview#85] opened 2015-03-06 18:33 UTC
Ran the Windows install on Windows 7.  Created the test app and the .css, .html and .js files are created correctly.  Cmd window returns that the app was created and to change to the new directory
and run the meteor command.   That results in an error message that the tasklist could not be found and it is typically located in ...

The tasklist is actually located where it should be.  Any suggestions would be appreciated.

**Comment by stubailo** [comment] 2015-03-06 18:45
So when you run the `tasklist` command in command prompt, it runs properly?

**Comment by thepowderriverfarrier** [comment] 2015-03-06 18:54
Yes sir.   That's what's so strange.   I can get Meteor to run on Linux just fine butnot on Windows 7.

**Comment by stubailo** [comment] 2015-03-06 20:00
Can you give me some more information? As I've never come across this issue it is very hard to diagnose, anything that could possibly be relevant will be helpful.

For example, what is the content of your %PATH% environment variable?

**Comment by avital** [comment] 2015-03-06 21:12
And if you run `where tasklist` from a command line prompt, what does it
print?

**Comment by thepowderriverfarrier** [comment] 2015-03-06 21:16
I'm sorry I am away from the office until Monday.  If I can remote in tomorrow morningI will send you the error message.

**Comment by thepowderriverfarrier** [comment] 2015-03-06 21:16
I'm sorry I am away from the office until Monday.  If I can remote in tomorrow morningI will send you the result of that command.

**Comment by thepowderriverfarrier** [comment] 2015-03-07 11:43
There's no 'where' command recognized by the default Windows set up butit looks like a reboot fixed the problem.  Was able to compile the test app andrun it under the 3000 port.   Thank you for your quick response.

**Comment by thepowderriverfarrier** [comment] 2015-03-07 11:45
Had C:\windows\system32 at the front of the path.  Had to reboot the boxremotely to reestablish some network connectivity and it appears that rebootsomehow did the trick.
Got the test app to compile and was able to view it under the 3000 port.   Thankyou for your rapid reponse.

**Comment by stuartbale** [comment] 2015-04-01 01:25
I have the same error on Windows Server 2012 R2. I am running command prompt as Admin.

I can run netstat from the same command line.

So what is the fix?

C:\meteor\simple-todos>meteor
[[[[[ C:\meteor\simple-todos ]]]]]

=> Started proxy.

C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local.meteor\packages\meteor-too
l\1.1.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
throw(ex);
^
Error: Couldn't run netstat -ano: {}
at Object.Future.wait (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
at findMongoPids (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:120:16)
at findMongoAndKillItDead (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Lo
cal.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:2
36:14)
at launchOneMongoAndWaitForReadyForInitiate (C:\Users\Administrator.WIN-OE3C
006M71I\AppData\Local.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\to
ols\run-mongo.js:360:7)
at launchMongo (C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local.meteor
\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:612:7)
at [object Object]..extend._startOrRestart (C:\Users\Administrator.WIN-OE3C
006M71I\AppData\Local.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\to
ols\run-mongo.js:712:19)
at [object Object]..extend.start (C:\Users\Administrator.WIN-OE3C006M71I\Ap
pData\Local.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mo
ngo.js:670:10)
at C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local.meteor\packages\met
eor-tool\1.1.1\mt-os.windows.x86_32\tools\run-all.js:199:26
- - - - -
at C:\Users\Administrator.WIN-OE3C006M71I\AppData\Local.meteor\packages\met
eor-tool\1.1.1\mt-os.windows.x86_32\tools\run-mongo.js:89:28
at ChildProcess.exithandler (child_process.js:654:7)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:766:16)
at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by thepowderriverfarrier** [comment] 2015-04-01 10:58
For running it on Windows 7 Professional it required a reboot before running meteor eventhough manually  running netstat/netstat -ano worked fine in a command prompt.

**Comment by romiohasan** [comment] 2015-05-01 11:00
I had the same problem on my Win64 8.1 ; added the C:\windows\system32 in the path variable- which was absent there. restart the pc but still didn't work. then removed the path of meteor in path variable; then again restart and again added the path of meteor back and again restart; after 4 times restart everything is working now! strange and wired!

**Comment by thepowderriverfarrier** [comment] 2015-05-01 11:13
A much easier solution was to quit using Windoze and just use Linux;  no problems at all.

**Comment by thepowderriverfarrier** [comment] 2015-06-05 13:31
It's happening again.   Error generated is: Couldn't run netstat -ano: {} at Object.Future.wait ...

Looks like Meteor really isn't ready to run on Windows.

**Comment by avital** [comment] 2015-06-05 16:27
@thepowderriverfarrier sorry for the inconvenience, we'll investigate this some more...

**Comment by thepowderriverfarrier** [comment] 2015-06-05 17:10
Thanks for the response.  It's been reinstalled if that's of anyhelp.  Using Windows 7.  Rebooting Windows sometimesresolves the issue but obviously that's not a viable solution.
It works fine without any issue on Linux Mint but we're required to be a Windows shop for production apps.

**Comment by avital** [comment] 2015-06-17 02:03
@thepowderriverfarrier, I just built a test release of Meteor to help expose what the error is. (The `{}` in the error message is supposed to be the error string, but it was printed poorly)

Could you try running your app with `meteor --release 1.1.0.2-diagnose-netstat-error`? Then if you get the error again please copy it here. It should give us some more information we can use to figure out the cause of the problem.

Apologies for the inconvenience, I really hope to get to the bottom of this.

**Comment by igor1z** [comment] 2015-06-17 05:57
executed  meteor --release 1.1.0.2-diagnose-netstat-error 
getting: Error: Couldn't run netstat -ano: Error: stdout maxBuffer exceeded.
Running Windows 7 Professional.

**Comment by avital** [comment] 2015-06-17 06:05
@igor1z thanks! that was my hunch -- could you do me one more favor? Run `netstat -ano` from a command prompt. How many lines more or less is the output?

**Comment by thepowderriverfarrier** [comment] 2015-06-17 10:44
Avital
I will remove Meteor do a reinstall and build a new Meteor app to test it.
Dan.

**Comment by thepowderriverfarrier** [comment] 2015-06-17 11:07
Did an uninstall of Meteor, reinstall of Metoer from the website, created a new basicMeteor app.
Got Downloading meteor-tool@1.1.4-aaa.4 for a few minutes then ...
=> Using Meteor 1.1.0.2-diagnoise-netstat-error as requested (overriding Meteor1.1.0.2)
[[[[[ C:\nginx-1.4.7\html\meteor\test ]]]]]
=> Started proxy.
CC:\Users\Dan\AppData\Local\.meteor\packages\meteor-tool\1.1.4.aaa.4\mt-os.windows.x86-32\dev_bundle\lib\node_modules\fibers\future.js:278                                                                 throw(ex);                                                                            ^Error:  Couldn't run netstat -ano: Error: stddout MaxBuffer exceeded.   at Object.Future.wait ... etc, etc, etc.


Running netstat -ano from a command prompt works as expected. 
No need to apologize for the inconvenience.  I'm happy to do whatever I can to makethis successful.  I work for a healthcare group in the DC area with a number of hospitals.I have a vested interest in looking good in my work.  <grin>  
Dan.

**Comment by igor1z** [comment] 2015-06-17 16:17
I got 97 lines running netstat -ano

**Comment by avital** [comment] 2015-06-17 17:48
Interesting. I don't see how a 97 line output from `netstat -ano` would surpass the 200KB default buffer to `child_process.exec` but I bumped the buffer size to 10MB, let's see if that fixes the problem.

Can you run you app with `meteor --release 1.1.0.2-diagnose-netstat-error-2` and see if the problem still happens?

**Comment by thepowderriverfarrier** [comment] 2015-06-17 17:53
Since it is Windows is it possible that the message is actually misleadingand not really reporting what's going on?

**Comment by igor1z** [comment] 2015-06-17 18:24
After restart of the machine problem was resolved. 

Ran meteor --release 1.1.0.2-diagnose-netstat-error-2 – no issues.

**Comment by thepowderriverfarrier** [comment] 2015-06-17 20:08
If it's any help I did that in the past ... restarted the machine andit solved the problem but only temporarily.  I will try it with thenewer release.

**Comment by thepowderriverfarrier** [comment] 2015-06-17 20:22
Reran it after a reboot.   Ran your requested command and it worked.  Was able tosee the demo site in the browser.
Then ran into the same problem we've been having all along.   We stopped the server via the cli then restarted it with the standard Meteor command and ran into the same problem re running netstat -ano.   Restarted Meteor with your suggested command line parameters and it worked fine again.
I hope this is of some help to you folks.
Dan.

**Comment by thepowderriverfarrier** [comment] 2015-06-18 12:14
For what it's worth this AM ran meteor with your suggested parameters thatworked yesterday but today we're getting the same error message we'vebeen getting all along re the couldn't run netstat -ano: Error:  stdout maxBuffer exceeded.That was after a Windows reboot.

**Comment by mnfilius** [comment] 2015-07-01 12:49
Hi
Trying to install Meteor 1.1 on Windows 7 (with full privileges) but also getting the "Couldn't  run tasklist.exe". 
Reboot and running the meteor --release 1.1.0.2-diagnose-netstat-error-2 command makes no difference. Current path looks very normal and also contains the path to
"<user>\AppData\Local\.meteor" 

Any ideas appreciated!
Thanks
Mark

**Comment by thepowderriverfarrier** [comment] 2015-07-01 13:10
That appears to be an ongoing issue with Windows 7 that has yet to be resolved.
That  meteor --release 1.1.0.2-diagnose-netstat-error-2 command did work a fewtimes but it hasn't worked in the last week or so.

**Comment by mnfilius** [comment] 2015-07-01 22:09
Thank you thepowderriverfarrier. We'll wait.

That appears to be an ongoing issue with Windows 7 that has yet to be resolved.
That  meteor --release 1.1.0.2-diagnose-netstat-error-2 command did work a fewtimes but it hasn't worked in the last week or so.

**Comment by avital** [comment] 2015-07-07 15:42
@thepowderriverfarrier (or anyone else who is hitting this problem) -- is there any way I could connect to your machine to help us diagnose this, maybe with Remote Desktop Connection?

**Comment by thepowderriverfarrier** [comment] 2015-07-07 16:48
We could try Teamviewer if I can get it up and running but I wouldn't postthe id/pwd in email.

**Comment by avital** [comment] 2015-07-07 16:50
@thepowderriverfarrier That could be great, can you shoot me an email at avital@meteor.com with the details?

**Comment by thepowderriverfarrier** [comment] 2015-07-08 08:42
Have Teamviewer up and running.   Will be here until 1200 Eastern Time today.

**Comment by mnfilius** [comment] 2015-07-08 12:32
We have fixed out problem. Needed to add /windows32 to the path. Rather strange!

**Comment by thepowderriverfarrier** [comment] 2015-07-08 14:15
There is no windows32.  Did you mean Windows/System32?

**Comment by thepowderriverfarrier** [comment] 2015-07-08 14:15
If you meant Windows/System32 that's already in the pathby default on the Windows OS.

**Comment by mnfilius** [comment] 2015-07-09 02:33
Hi

Yes I meant that folder.
Thats also what makes it so strange.  
We did:
 fresh install of meteor > same problem > added the path > fixed

cheers
mark

Date: Wed, 8 Jul 2015 07:15:08 -0700

**Comment by thepowderriverfarrier** [comment] 2015-07-09 08:50
That folder has always been in the path.

**Comment by mnfilius** [comment] 2015-07-10 08:01
Exactly! That's what makes it so strange!


thepowderriverfarrier wrote:
> That folder has always been in the path.
> From: mnfilius <notifications@github.com>
> To: meteor/windows-preview <windows-preview@noreply.github.com>
> Cc: thepowderriverfarrier <thepowderriverfarrier@yahoo.com>
> Sent: Wednesday, July 8, 2015 10:33 PM
> Subject: Re: [windows-preview] netstat or tasklist not found (#85)
>
> Hi
>
> Yes I meant that folder.
> Thats also what makes it so strange.
> We did:
> fresh install of meteor > same problem > added the path > fixed
>
> cheers
> mark
>
> Date: Wed, 8 Jul 2015 07:15:08 -0700
> From: notifications@github.com
> To: windows-preview@noreply.github.com
> CC: mark@filius.cc
> Subject: Re: [windows-preview] netstat or tasklist not found (#85)
>
> If you meant Windows/System32 that's already in the pathby default on 
> the Windows OS.
>
> From: mnfilius <notifications@github.com>
>
> To: meteor/windows-preview <windows-preview@noreply.github.com>
>
> Cc: thepowderriverfarrier <thepowderriverfarrier@yahoo.com>
>
> Sent: Wednesday, July 8, 2015 8:32 AM
>
> Subject: Re: [windows-preview] netstat or tasklist not found (#85)
>
>
>
> We have fixed out problem. Needed to add /windows32 to the path. 
> Rather strange!—
>
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/meteor/windows-preview/issues/85#issuecomment-119878466>.
>


Kind regards
Mark Filius
E: mark@filius.cc <mailto:mark@filius.cc>
P: +61 (0)7 3848 6039
M: +61 (0)4 1 3456 832
S: markfilius

**Comment by thepowderriverfarrier** [comment] 2015-07-10 09:48
We're still left with the situation where Meteor will not work on Windows 7.The System32 folder is in/has been in the path the whole time.

**Comment by mnfilius** [comment] 2015-07-10 11:09
All I can say is that, in our case, adding the System32 folder to the 
front(!) of the path was the solution

thepowderriverfarrier wrote:
> We're still left with the situation where Meteor will not work on 
> Windows 7.The System32 folder is in/has been in the path the whole time.
> From: mnfilius <notifications@github.com>
> To: meteor/windows-preview <windows-preview@noreply.github.com>
> Cc: thepowderriverfarrier <thepowderriverfarrier@yahoo.com>
> Sent: Friday, July 10, 2015 4:01 AM
> Subject: Re: [windows-preview] netstat or tasklist not found (#85)
>
> Exactly! That's what makes it so strange!
>
>
> thepowderriverfarrier wrote:
> > That folder has always been in the path.
> > From: mnfilius <notifications@github.com>
> > To: meteor/windows-preview <windows-preview@noreply.github.com>
> > Cc: thepowderriverfarrier <thepowderriverfarrier@yahoo.com>
> > Sent: Wednesday, July 8, 2015 10:33 PM
> > Subject: Re: [windows-preview] netstat or tasklist not found (#85)
> >
> > Hi
> >
> > Yes I meant that folder.
> > Thats also what makes it so strange.
> > We did:
> > fresh install of meteor > same problem > added the path > fixed
> >
> > cheers
> > mark
> >
> > Date: Wed, 8 Jul 2015 07:15:08 -0700
> > From: notifications@github.com
> > To: windows-preview@noreply.github.com
> > CC: mark@filius.cc
> > Subject: Re: [windows-preview] netstat or tasklist not found (#85)
> >
> > If you meant Windows/System32 that's already in the pathby default on
> > the Windows OS.
> >
> > From: mnfilius <notifications@github.com>
> >
> > To: meteor/windows-preview <windows-preview@noreply.github.com>
> >
> > Cc: thepowderriverfarrier <thepowderriverfarrier@yahoo.com>
> >
> > Sent: Wednesday, July 8, 2015 8:32 AM
> >
> > Subject: Re: [windows-preview] netstat or tasklist not found (#85)
> >
> >
> >
> > We have fixed out problem. Needed to add /windows32 to the path.
> > Rather strange!—
> >
> > Reply to this email directly or view it on GitHub.
> >
> >
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
> >
> >
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/meteor/windows-preview/issues/85#issuecomment-119878466>.
> >
>
>
> Kind regards
> Mark Filius
> E: mark@filius.cc <mailto:mark@filius.cc>
> P: +61 (0)7 3848 6039
> M: +61 (0)4 1 3456 832
> S: markfilius
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/meteor/windows-preview/issues/85#issuecomment-120326017>.
>


Kind regards
Mark Filius
E: mark@filius.cc <mailto:mark@filius.cc>
P: +61 (0)7 3848 6039
M: +61 (0)4 1 3456 832
S: markfilius

**Comment by thepowderriverfarrier** [comment] 2015-07-10 11:34
That's no help at all then.

**Comment by thepowderriverfarrier** [comment] 2015-07-21 14:17
FYI:  We did another removal of Meteor and downloaded the install forWindows from the Meteor site this AM.  It looks like it may be finally working for Windows 7.  No changes were made to the PATH on the Windows box.

**Comment by stubailo** [comment] 2015-08-11 19:02
This conversation should continue here: https://github.com/meteor/meteor/issues/4128

I'm closing this repo since Meteor on Windows is no longer in the preview stage.

**Closed by stubailo** 2015-08-11 19:02 UTC
Labels: tasklist
