### ISSUE TITLE
meteor mongo: couldn't run tasklist

### ISSUE THREAD

**Issue by DmitryZhidkov** [meteor/windows-preview#71] opened 2015-02-17 11:02 UTC
Meteor install on windows 2003 enterprise edition x64 sp2
After run app - result:

```
C:\www\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: Couldn't run tasklist: {"killed":false,"code":1,"signal":null}
    at Object.Future.wait (C:\www\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at findMongoPids (C:\www\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.win
dows.x86_32\tools\run-mongo.js:116:16)
    at findMongoPort (C:\www\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.win
dows.x86_32\tools\run-mongo.js:168:14)
    at Command.main.registerCommand.name [as func] (C:\www\.meteor\packages\mete
or-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\commands.js:967:21)
    at C:\www\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\too
ls\main.js:1334:23
    - - - - -
    at C:\www\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\too
ls\run-mongo.js:69:24
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

![summary](https://cloud.githubusercontent.com/assets/7954266/6457285/9af325d4-c184-11e4-9933-e4e29d34e95c.png)
![os](https://cloud.githubusercontent.com/assets/7954266/6457284/9af2ed44-c184-11e4-9682-33109cd04307.png)
![supermicro_motherboard](https://cloud.githubusercontent.com/assets/7954266/6457286/9af8762e-c184-11e4-9d11-05dadfd3a198.png)

**Comment by Slava** [comment] 2015-02-23 03:18
When does it happen? How can we reproduce it? We need more information to debug this.

**Comment by powpow12** [comment] 2015-02-28 11:45
I am having a similar issue, 
Windows: 8.1 
Meteor Preview: 0.1.7
Issue: After installing .exe, successfully created the todo's directory and necessary files.  However, when I cd todos and run meteor I get the following error message:
[[[[[ C:\Users\User\Documents\vagrant+meteor\project\simple-todos ]]]]]

=> Started proxy.

C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
						throw(ex);
						      ^
Error: Couldn't run tasklist: {"code":"ENOENT","errno":"ENOENT","syscall":"spawn"}
    at Object.Future.wait (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at findMongoPids (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:116:16)
    at findMongoAndKillItDead (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:191:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:310:7)
    at launchMongo (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:562:7)
    at [object Object]._.extend._startOrRestart (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:662:19)
    at [object Object]._.extend.start (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:620:10)
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-all.js:194:26
    - - - - -
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:69:24
    at exithandler (child_process.js:654:7)
    at ChildProcess.errorhandler (child_process.js:670:5)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:818:12)

**Comment by DmitryZhidkov** [comment] 2015-03-02 10:21
install on windows 2003 enterprise edition x64 sp2

**Comment by Slava** [comment] 2015-03-03 03:26
@powpow12 can you please give me more information about your OS? Is it some flavor of Windows that comes with a laptop? Or perhaps it is an ARM version (WinRT?).

Another possible workaround, try installing system updates for your OS. I found this update that supposedly fixes `tasklist` for a variety of OSes: http://support.microsoft.com/kb/2732840.

**Comment by DmitryZhidkov** [comment] 2015-03-03 06:03
![summary](https://cloud.githubusercontent.com/assets/7954266/6457251/0c506030-c184-11e4-845d-cd06faa9ccaf.png)
![os](https://cloud.githubusercontent.com/assets/7954266/6457253/0c5855a6-c184-11e4-9e67-2e43b0221ba8.png)
![supermicro_motherboard](https://cloud.githubusercontent.com/assets/7954266/6457252/0c50a450-c184-11e4-9283-3ac983957f50.png)

**Comment by romantaraban** [comment] 2015-03-03 22:48
I have the same issue as posted in the first message, when run "meteor run". Running win 8.1 and Meteor 0.1.7
```
D:\work\test2>meteor run
[[[[[ ~\D\work\test2 ]]]]]

=> Started proxy.

C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.j
s:278
                                                throw(ex);
                                                      ^
Error: Couldn't run tasklist: {"killed":false,"code":1,"signal":null}
    at Object.Future.wait (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\lib\n
ode_modules\fibers\future.js:398:15)
    at findMongoPids (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:11
6:16)
    at findMongoAndKillItDead (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mo
ngo.js:191:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x
86_32\tools\run-mongo.js:310:7)
    at launchMongo (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:562:
7)
    at [object Object]._.extend._startOrRestart (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x
86_32\tools\run-mongo.js:662:19)
    at [object Object]._.extend.start (C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tool
s\run-mongo.js:620:10)
    at C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-all.js:194:26
    - - - - -
    at C:\Users\Roman\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-mongo.js:69:24
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by powpow12** [comment] 2015-03-05 13:28
@Slava I have windows 8.1 on a toshiba laptop. I can provide more specific specs if you tell me what you need.

**Comment by Slava** [comment] 2015-03-05 18:20
@powpow12 can you please reply to my questions above and check if you have the tasklist utility on your system. If not, does installing the system update mentioned above help?

**Comment by sdarnell** [comment] 2015-03-05 21:52
It would also be good to include what your path contains. Use `set path` or `echo %PATH%` to print out the value.

**Comment by romantaraban** [comment] 2015-03-08 09:21
In my case (with Error: Couldn't run tasklist: {"killed":false,"code":1,"signal":null}) the problem was with cmd.exe and not related to Meteor or MongoDB.

**Comment by stubailo** [comment] 2015-03-09 17:58
@romantaraban what do you mean the problem was with your cmd.exe?

**Comment by romantaraban** [comment] 2015-03-09 19:28
@stubailo there was a record in HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun which pointed to a removed extension (Ansicon). This issue threw errors for ANY command executed under Nodejs. After removing the record everything works perfectly.

**Comment by DmitryZhidkov** [comment] 2015-03-11 06:22
I do not have autorun folder in the branch HKEY_CURRENT_USER \ Software \ Microsoft \ Command Processor, so the problem is not solved

**Comment by stubailo** [comment] 2015-03-11 17:40
```
C:\Documents and Settings\zhidkov\Local Settings\Application Data\.meteor\
```

Ah, that's pretty different from the path you get on Windows 7 or 8. I just noticed you are running Windows 2003, which we are probably not going to be able to officially support. Are there a lot of people using this operating system? Since the end of life is this July, will you be upgrading soon?

**Comment by avital** [comment] 2015-04-10 00:59
There are three reports here:

* @DmitryZhidkov's report is on Windows 2003, which isn't one of Meteor's [supported platforms](https://github.com/meteor/meteor/wiki/Supported-Platforms).

* @romantaraban seems to have [fixed his issue](https://github.com/meteor/windows-preview/issues/71#issuecomment-77924368)

* @powpow12 hasn't responded for over a month. (Maybe @romantaraban's solution above solves your problem?) 

So I'll close this ticket. If there are still problems (or, @powpow12, if the suggestion above doesn't help), please file an issue against the [meteor/meteor](https://github.com/meteor/meteor) repository. This repository will be closed soon.

**Closed by avital** 2015-04-10 00:59 UTC
Labels: tasklist
