### ISSUE TITLE
MongoDB had an unspecified uncaught exception

### ISSUE THREAD

**Issue by AnnotatedJS** [meteor/windows-preview#132] opened 2015-03-21 10:29 UTC
Installing was ok
Creating new Meteor project also ok
With running the meteor project I got the following,

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

**Comment by stubailo** [comment] 2015-03-25 04:49
Duplicate of #8

**Closed by stubailo** 2015-03-25 04:49 UTC

**Comment by AnnotatedJS** [comment] 2015-03-25 08:03
Hi Sashko,

Thanks for taking time to respond to my issue.
I tried again to install an app which gave the same issue) and finally 
worked/stumbled my way to a solution.
I posted the following comment on #8 
<https://github.com/meteor/windows-preview/issues/8>

Greetings,
Rene

====================================

My comment is related to the issue of original poster (more so to his 
second posting) I never had the error message http.js:732 throw new 
Error as described by fafournier

I checked the properties of the folders based on the suggestion, "Check 
that you have permissions to write to .meteor/local."

I did not have that permission. Tried several ways to uncheck this 
setting. This didn't work.

See for instance "In Windows 8 64, Can not remove read only attribute 
from folder inside of a programData folder" 
http://answers.microsoft.com/en-us/windows/forum/windows_8-files/in-windows-8-64-can-not-remove-read-only-attribute/b21c0629-58dd-477d-ae06-39c982b1cdd1 
for a lot of frustrated postings.

However reading that discussion I realized that the problem was related 
to the fact that C:\Users is a Windows system folder

Therefore create a meteor app on D: and it worked as intended.

**Comment by stubailo** [comment] 2015-03-25 17:04
Thanks @AnnotatedJS! Going to look at your comment there. Sorry for being so terse when I replied, I was in a hurry.
