### ISSUE TITLE
Meteor mongo - Meteor isn't running a local MongoDB server.

### ISSUE THREAD

**Issue by tnedich** [meteor/windows-preview#72] opened 2015-02-18 13:21 UTC
Win7 Ultimate 64 - bit
File system: NTFS
windows-preview  0.1.7
Meteor mongo won't start.

***mongo: Meteor isn't running a local MongoDB server.***

**Comment by lpartan** [comment] 2015-02-18 23:59
I had the mongoDB (and other parts) become terminally ill several times yesterday.  Win8.1 64bit. A couple of times meteor was able to get mongoDB going again, but was unable to rebuild the app.  When "meteor reset" or "meteor"  seems to go on forever, it probably will, so just use Ctrl-C to abort the batch run.

Three things worked for me.  In order of rising severity, try one and then try starting the app with "meteor". After each one, if the command "meteor" can't get it going, try the next one.

1.  Delete the mongo lock file (sometimes it doesn't get cleared away): it's name is mongod.lock, It's in your current METEOR_APP_DIRECTORY  here:  \.meteor\local\db\mongod.lock   Just delete it. Then retry "meteor" to run the app.  You'll keep your database records.

2.  Try running "meteor reset" (you'll lose all database records).  Then retry "meteor" to run the app.

3.  Delete the folder called "local".  Just delete the whole thing and all of its folders and files. It's METEOR_APP_DIRECTORY\.meteor\local   It's like a 'deep reset'.  Then retry "meteor" to run the app.   

Number 3 worked when nothing else would.

**Comment by stubailo** [comment] 2015-03-05 05:44
This might be fixed in the newest release. Try updating your app: `meteor update --release WINDOWS-PREVIEW@0.2.0`

**Comment by tnedich** [comment] 2015-03-05 11:47
No, still same problem. Now  **meteor update** trows bunch of errors

Win7 Ultimate 64 - bit
File system: NTFS
windows-preview 0.2.0
**io.js platform**
Meteor mongo won't start.

**Comment by tnedich** [comment] 2015-03-05 11:54
@lpartan Thank You for your time. I have tried all three steps, but it is not working. :(

**Comment by xMisax** [comment] 2015-03-16 20:36
i have the same problem....mongodb dosent work.

**Comment by tnedich** [comment] 2015-03-17 16:08
Win7 Ultimate 64 - bit
File system: NTFS
WINDOWS-PREVIEW@0.3.0
Meteor mongo won't start.

***mongo: Meteor isn't running a local MongoDB server.***

Still the same problem. @xMisax

**Comment by wordsearchbob** [comment] 2015-03-17 20:15
Win7 Pro 64-bit
WINDOWS-PREVIEW@0.3.0

> meteor mongo

Received the same error message as everyone else above. After poking around on Stack Exchange I found:

> mongo localhost:3001/meteor

Which successfully connected me to the local database for my app running on localhost:3000.

**Comment by wordsearchbob** [comment] 2015-03-17 21:02
I did some more digging and found this line in the [run-mongo.js](https://github.com/meteor/meteor/blob/9a29988016b405298fbfe2b8540a6aa3d8b518ad/tools/run-mongo.js#L174) script.

It appears that the findMongoPort function is expecting exactly 1 active mongo process. If !== 1, it returns null.

I found that I had 3 mongo processes in my Task Manager for some reason. I killed them all, restarted my meteor app, and now the "meteor mongo" command works for me.

**Comment by tnedich** [comment] 2015-03-17 22:10
@wordsearchbob  Thank you man. I am not that smart or intuitive (not thinking to much) I have set mogno to run as service when windows starts. After killing that proces everything works just fine. Thumbs up man and thank you for your time. I will close this issue for now.

**Comment by stubailo** [comment] 2015-03-17 23:47
We should keep this open because having a mongo process running is a pretty reasonable thing for people to do.

**Comment by Slava** [comment] 2015-03-21 00:03
Should be fixed in https://github.com/meteor/meteor/commit/155375da1f9281638ef6e9a340fecabdbc850a30. Also a possible duplicate of #40.

**Comment by stubailo** [comment] 2015-03-21 00:40
Will close when the fix is released

**Comment by Slava** [comment] 2015-03-26 17:42
Fixed in 1.1RC0

**Closed by Slava** 2015-03-26 17:42 UTC

**Comment by manuelmateus16** [comment] 2015-04-06 00:04
I am in 1.1.0.1 version and with meteor running in a shell window, when attempting to connect to the local mongodb database i obtain the same error:
"mongo: Meteor isn't running a local MongoDB server."

I haven't specified a $MONGO_URL.

**Comment by krishprasadar** [comment] 2015-07-03 17:59
Same here

**Comment by tnedich** [comment] 2015-07-03 20:52
In Meteor 1.1.0.2 everything works fine for me.
