### ISSUE TITLE
Can't follow tutorial

### ISSUE THREAD

**Issue by davidlighty** [meteor/windows-preview#54] opened 2015-02-05 15:15 UTC
Running 1.6, the event handling of a form submit doesn't work.  Rather it does a full postback.  Putting a preventDefault in the submit does allow the form to be processed, but then 'event.target.text' does not exist either.

**Comment by stubailo** [comment] 2015-02-05 16:23
What web browser are you testing in? This sounds like a client-side issue which shouldn't be affected by the OS you are running.

**Comment by davidlighty** [comment] 2015-02-05 17:07
Latest ff on win 8.1

-----Original Message-----

**Comment by landmaxcanada** [comment] 2015-02-05 19:52
Version 1.6 seems to have broken the simple-todo demo for me as well. Was working fine with 1.5, then I did an upgrade to 1.6 and got this error:

"D:\_2015-Websites\Samples\Simple-Todos\simple-todos>meteor
[[[[[ ~\D\_2015-Websites\Samples\Simple-Todos\simple-todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
D:\_2015-Websites\Samples\Simple-Todos\simple-todos>"

I am using Win7 x64, rebooted computer and error remained.

**Comment by stubailo** [comment] 2015-02-05 20:15
in this case, try deleting `.meteor/local/db/mongo.lock` inside your project.

**Comment by landmaxcanada** [comment] 2015-02-05 20:34
Yes, that fixed it, but the file is called mongod.lock

**Comment by stubailo** [comment] 2015-02-06 00:50
Thanks, we're aware of this issue so I'm going to close this.

**Closed by stubailo** 2015-02-06 00:50 UTC

**Comment by davidlighty** [comment] 2015-02-13 03:51
Just as an update, I'm still getting a full postback on events.  With just a 'click .someElement':function(){} runs twice.  This is with 1.7
