### ISSUE TITLE
False Positive Virus Detected .2

### ISSUE THREAD

**Issue by tdhz77** [meteor/windows-preview#87] opened 2015-03-07 02:02 UTC
InstallMeteor.exe downloaded from github reported by Symantec Virus Scan as containing WS.Reputation.1 -- FYI, Obviously nothing to worry about. I'm on a corporate computer, so I'm unable to install ATM.

**Comment by stubailo** [comment] 2015-03-07 02:12
Can you give use a screenshot of the message from the scanner, or some log data? More information will be helpful, in addition to the version of the virus scanner.

**Comment by sdarnell** [comment] 2015-03-07 08:21
Seems to be simply a "not many users have installed this therefore it may be dodgy" warning.
It should be possible to recover the file from the quarantine.

From a developers perspective the only help I have seen is to ensure you have a proper certificate and this white listing service:
https://submit.symantec.com/whitelist/

But that is still a pain.

**Comment by stubailo** [comment] 2015-03-10 02:15
Yeah we're going to sign the installer in the future.

**Comment by stubailo** [comment] 2015-03-20 18:24
Duplicate of #65 at this point.

**Closed by stubailo** 2015-03-20 18:24 UTC
