### ISSUE TITLE
Mongodb exit code 100 when running "meteor"

### ISSUE THREAD

**Issue by ciwolsey** [meteor/windows-preview#8] opened 2014-11-26 04:06 UTC
C:\Users\ciwolsey\Desktop>meteor create sausages
sausages: created.

To run your new app:
   cd sausages
   meteor

C:\Users\ciwolsey\Desktop>cd sausages

C:\Users\ciwolsey\Desktop\sausages>meteor
[[[[[ C:\Users\ciwolsey\Desktop\sausages ]]]]]

=> Started proxy.
=> Started MongoDB.
   Building the application                  -
C:\Users\ciwolsey\Desktop\sausages>
C:\Users\ciwolsey\Desktop\sausages>meteor run
[[[[[ C:\Users\ciwolsey\Desktop\sausages ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
   Starting MongoDB                          -
C:\Users\ciwolsey\Desktop\sausages>meteor
[[[[[ C:\Users\ciwolsey\Desktop\sausages ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
   Starting MongoDB                          |
C:\Users\ciwolsey\Desktop\sausages>

**Comment by dvenske** [comment] 2015-01-20 11:19
It seems like exfat file systems wont work either and throw the same error as reported here. I had to make a FAT32 partition for it to work.

**Comment by stubailo** [comment] 2015-01-20 19:03
Does it work on NTFS?

**Comment by sdarnell** [comment] 2015-02-05 22:33
Hi @ciwolsey you should not need to run as an admin, and I would discourage that. Though it is very strange that it appeared to work in that scenario (from your gist link).
As a regular user, could you do a `meteor reset` in the application directory, and then try to restart?

If this doesn't work, I suspect there may be an existing mongodb process still running. Please check from task manager, or from the command line with `tasklist | findstr mongo`

Another possibility is that one of the mongodb files is in use. So the surest way to test this, is to reboot, then do a `meteor reset`, then `meteor`.

**Comment by sdarnell** [comment] 2015-02-05 22:41
If all of that fails to help, I would suggest using the sysinternals process monitor to capture what is going on during the startup and see if you can see which file system operation is failing.

By the way, exit code 100 is documented to be an 'uncaught exception` : http://docs.mongodb.org/manual/reference/exit-codes/

It may help to specify -vvvvv on the command line to mongod.exe, but that probably requires a minor tweak to the code that executes mongod.exe

**Comment by ciwolsey** [comment] 2015-02-06 01:00
I've just tested this on a fresh install of windows 8.1 (same computer though) and the install went smooth and meteor started just fine. If nobody else can reproduce this I think it could be closed?

**Comment by Slava** [comment] 2015-02-06 01:04
The problem still exists, it just takes some "luck" to reproduce it.

**Comment by fafournier** [comment] 2015-02-16 17:12
So, got a similar error, if first runs for a while, then this happens:
- http.js:732    throw new Error('Can\'t render headers after they are sent to the client.'
upon restarting meteor: Unexpected mongo exit code 100. Restarting. Can't start Mongo server.
then, deleting "C:\Users\ABC\GitHub\newmeteorapp\.meteor\local\db\mongo.lock" or doing "meteor reset" solves the problem for a while, then it crashes again later.

The error always seems to start with a http.js:732 error. Hope that helps.

----------------
=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted

http.js:732
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:732:11)
    at ServerResponse.writeHead (http.js:1153:20)
    at ProxyServer.<anonymous> (C:\Users\ABC\AppData\Local\.meteor\packages\meteo
r-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\run-proxy.js:96:21)
    at ProxyServer.emit (C:\Users\ABC\AppData\Local\.meteor\packages\meteor-tool\
1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\eventemitter3\inde
x.js:100:27)
    at ClientRequest.proxyError (C:\Users\ABC\AppData\Local\.meteor\packages\mete
or-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\http-proxy
\lib\http-proxy\passes\web-incoming.js:140:16)
    at ClientRequest.emit (events.js:117:20)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
C:\Users\ABC\GitHub\newmeteorapp>meteor
[[[[[ C:\Users\ABC\GitHub\newmeteorapp]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

**Comment by 255kb** [comment] 2015-02-21 15:30
@fafournier I have exactly the same error from time to time: 'Can\'t render headers after they are sent to the client.'
I have to remove *.Meteor/local/db/mongod.lock*, so I can rerun Meteor as it seems to have crashed.
I haven't figured out yet the cause of this bug.

**Comment by smeijer** [comment] 2015-02-25 13:24
Exactly the same error as @fafournier and @255kb. Running at Windows 8.1 (all latest updates), and had node v0.12.0 already installed before installing Meteor (not sure if that matters).

**Comment by benjamin79** [comment] 2015-02-26 13:22
I´ve the same error on windows 10 (exFAT) though. Fresh install. After doing meteor reset it works.

**Comment by 255kb** [comment] 2015-03-12 13:58
Since 0.2.0 I have a lot less of this error. The only time I got it is when I pressed F5 in my browser (even if I know it is useless :)) during a rebuild from the server

**Comment by AnnotatedJS** [comment] 2015-03-25 07:57
My comment is related to the issue of original poster (more so to his second posting) I never had the error message http.js:732 throw new Error as described by fafournier

I checked the properties of the folders based on the suggestion, "Check that you have permissions to write to .meteor/local."

I did not have that permission. Tried several ways to uncheck this setting. This didn't work. 

See for instance "In Windows 8 64, Can not remove read only attribute from folder inside of a programData folder" http://answers.microsoft.com/en-us/windows/forum/windows_8-files/in-windows-8-64-can-not-remove-read-only-attribute/b21c0629-58dd-477d-ae06-39c982b1cdd1 for a lot of frustrated postings.

However reading that discussion I realized that the problem was related to the fact that C:\Users is a Windows system folder

Therefore create a meteor app on D: and it worked as intended.

**Comment by stubailo** [comment] 2015-03-25 17:05
@AnnotatedJS - this is great information! Where were you creating the app before? Directly in `C:\Users`?

**Comment by AnnotatedJS** [comment] 2015-03-25 17:44
Yes, as was the original poster of #8

And no hard feelings about your terse writing style.

**Comment by Slava** [comment] 2015-03-28 00:29
I just found out that mongo also fails to run in a folder that has Cyrillic chars on its path (or any unicode non-latin chars I guess).

**Comment by avital** [comment] 2015-04-10 00:32
I just set up Windows 8 and was unable to reproduce this with Meteor 1.1.

@ciwolsey, @AnnotatedJS does this still happen to you with the latest version of Meteor?

**Comment by ciwolsey** [comment] 2015-04-10 01:34
@avital While I'm not using Meteor for Windows regularly - once the official release came I gave it a try and it worked smoothly for me. I haven't experienced any issue since.

**Comment by AnnotatedJS** [comment] 2015-04-10 05:40
@avital Like I previous mentioned. I have placed my projects folder outside the c:/Users folder and that works fine. My name is René so the complete path was c:\Users\René. As Slava commented, maybe it is the character 'é' that caused the problem.

Currently happy coding with Meteor.

**Comment by avital** [comment] 2015-04-10 14:44
@AnnotatedJS Ah. Good to know -- it's probably the 'é' character that caused the issue.

Closing as a dupe of https://github.com/meteor/windows-preview/issues/145

**Comment by lance-anderson** [comment] 2015-04-13 17:00
Just an FYI— I came in Monday morning and had this problem at startup on my MacBook Pro.
```
Unexpected mongo exit code 100. Restarting.
```
Restarting my computer and deleting the mongo.lock file didn't help but running ```meteor reset``` did the trick. Thank you!

**Comment by lance-anderson** [comment] 2015-04-14 05:23
FWIW— it may or may not be relevant... probably a rathole... but I'm using Google Drive to sync my project files. In the past I've used Dropbox and the syncing has been perfect. I'm only a few weeks in with Google Drive and I've encountered a couple of issues. It doesn't just work like Dropbox does. I've noticed it fiddles with files and has some odd behaviors. Several times it has duplicated numerous files in Finder saving the duplicates as "settings.js (1)". 

Anyway... perhaps the syncing of Google Drive was the culprit in my particular encounter with this bug. If i encounter it again I'll be sure to save a copy of my project directory. Let me know if there is any other debug info that would be helpful for reproducing.

**Comment by avital** [comment] 2015-04-14 05:24
Interesting. I'll update the title here to reflect that it happens with Google Drive, thanks for the info.

**Comment by avital** [comment] 2015-04-14 05:26
(Ah; you're not sure that it's related...)

**Comment by stijnbuurman** [comment] 2015-05-31 14:43
I am having this issue on windows 8.1 on my exfat drive. On NTFS it just works.
I tried everything, restarting, deleting lock file, deleting whole local folder, meteor reset.. 

```
=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
```

**Comment by redhelix** [comment] 2015-08-06 02:48
Had this issue today on Windows 10 - Ran it on an exFat partition  and it failed with:

=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

Switch over to NTFS partition, and it started up no problem

... Could exFat be the issue?

**Comment by sdarnell** [comment] 2015-08-06 07:04
http://docs.mongodb.org/manual/administration/production-checklist/
"Windows: use the NTFS file system. Do not use any FAT file system (i.e. FAT 16/32/exFAT)."

It isn't clear whether that is for performance reasons or for functional reasons.

**Comment by stubailo** [comment] 2015-08-11 19:00
Moving this here: https://github.com/meteor/meteor/issues/4936

I'm closing this repo.

**Closed by stubailo** 2015-08-11 19:00 UTC
Labels: bug
