### ISSUE TITLE
Cant deploy on Meteor.com

### ISSUE THREAD

**Issue by engenheiro** [meteor/windows-preview#82] opened 2015-03-01 16:12 UTC
I having problems to deploy my project on Meteor, its return a error about the version. I have tried some solutions, like modifying the min version on the boot.js file, but not work.

**Comment by Slava** [comment] 2015-03-01 18:10
closing as a duplicate of https://github.com/meteor/windows-preview/issues/64

**Closed by Slava** 2015-03-01 18:10 UTC
