### ISSUE TITLE
Not possible to update useraccounts based packages

### ISSUE THREAD

**Issue by tcastelli** [meteor/windows-preview#79] opened 2015-02-25 14:43 UTC
Not sure if this is due to some windows specific limitations on the preview, but when i try to update some packages like useraccounts:core or useraccounts:bootstrap i get this message

meteor add useraccounts:bootstrap@1.8.1
 => Errors while adding packages:

While selecting package versions:
error: conflict: constraint http@1.0.10 is not satisfied by 1.0.10-winr.5.
Constraints on http come from:
<top level>
meteor-platform@1.2.1-winr.3 -> autoupdate@1.1.5-winr.4
useraccounts:bootstrap@1.8.1 -> useraccounts:core@1.8.1

**Comment by sdarnell** [comment] 2015-02-25 21:49
Probably one for MDG to answer, but this issue should disappear when standard packages are used instead of the '-winr.3' or '-winr.4' etc. variants. However, I'm a little bit surprised that there is this inconsistency in the meteor-platform@1.2.1-winr.3 dependency chain.

**Comment by stubailo** [comment] 2015-02-25 21:52
The problem is that we specified the wrong version: we should have published `http@1.0.11-winr.5`, which would have satisfied that requirement.

This release is a little weirder than the others due to basically every single version number changing.

**Comment by stubailo** [comment] 2015-03-05 05:41
This should be fixed in the newest release - try `meteor update --release WINDOWS-PREVIEW@0.2.0`.

**Closed by stubailo** 2015-03-05 05:41 UTC
Labels: bug
